Add streak model
ignaoya/habit_nuker pull request #18
Opened 2022-11-24 15:29 UTC by ignaoya

2022-11-24 17:28 UTC, nicky-eng requested changes

2022-11-24 17:28 UTC, nicky-eng commented on tracker/migrations/0002_streak.py
> +                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 11, 24, 15, 17, 56, 608448, tzinfo=datetime.timezone.utc))),
datetime causing migration warnings. Please, resolve!

2022-11-24 17:28 UTC, nicky-eng commented on tracker/migrations/0002_streak.py
> +                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 11, 24, 15, 17, 56, 608505, tzinfo=datetime.timezone.utc))),
Same here!

2022-11-24 17:28 UTC, nicky-eng commented on tracker/models.py
> +    start_date = models.DateTimeField(default=timezone.now())
Fix this to fix migrations

2022-11-26 12:38 UTC, nicky-eng approved these changes
Can you post the StackOverflow link you followed to solve this problem?

2022-11-29 13:17 UTC, ignaoya commented
The resolution was found in the first answer to this question:
https://stackoverflow.com/questions/2771676/django-datetime-issues-default-datetime-now

2022-11-29 13:18 UTC, ignaoya commented on tracker/migrations/0002_streak.py
> +                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 11, 24, 15, 17, 56, 608448, tzinfo=datetime.timezone.utc))),
Migration issue resolved.

2022-11-29 13:18 UTC, merged